version: "3.8"

services:
  app:
    image: php:8.2-apache
    container_name: healthy-meals-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:YOUR_APP_KEY_HERE
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: healthy_meals
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    command: >
      bash -c "composer install --ignore-platform-reqs && php artisan migrate --force && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: healthy-meals-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: healthy_meals
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
